/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AnthropicApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ArtifactsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "DatabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DocQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "DocQueueDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "Embedder": {
      "name": string
      "type": "sst.aws.Function"
    }
    "EmbeddingQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "EmbeddingQueueDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "FalKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FileIngestionQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "FileIngestionQueueDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "FileRouter": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GraphRecalc": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GraphRecalcQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "GraphRecalcQueueDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ImageGenQueueDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ImageGenerationQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ImageGenerator": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ImageQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ImageQueueDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "LessonTextGenerationQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "LessonTextGenerationQueueDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "LessonTextGenerator": {
      "name": string
      "type": "sst.aws.Function"
    }
    "OriginalsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "PdfProcessor": {
      "name": string
      "type": "sst.aws.Function"
    }
    "PdfQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "PdfQueueDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "SupabaseServiceRoleKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SupabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "VideoQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "VideoQueueDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "VoyageApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}

import "sst"
export {}